### ISSUE TITLE
欢迎弹幕不能使用

### ISSUE THREAD

**Issue by yaalyy** [BanqiJane/Bilibili_Danmuji#13]
欢迎弹幕的设置不能保存，刷新后会空白

Cannot invoke "xyz.acproject.danmuji.conf.set.ThankWelcomeSetConf.isIs_tx_shield()" because the return value of "xyz.acproject.danmuji.conf.CenterSetConf.getWelcome()" is null

**Comment by BanqiJane** [comment]
我这边无法复现呢 有完整日志吗 推测是配置文件没更新到新参数

**Comment by yaalyy** [comment]
从房间连接就开始出问题了

**Comment by yaalyy** [comment]
2021-05-04 16:33:28,178 DEBUG Websocket:37 -websocket connect open(连接窗口打开)
2021-05-04 16:33:28,179 DEBUG WebSocketProxy:27 -Connecting Success(连接成功)
java.lang.NullPointerException: Cannot invoke "xyz.acproject.danmuji.conf.set.ThankWelcomeSetConf.isIs_tx_shield()" because the return value of "xyz.acproject.danmuji.conf.CenterSetConf.getWelcome()" is null
	at xyz.acproject.danmuji.tools.ParseSetStatusTools.getMessageConcurrentHashMap(ParseSetStatusTools.java:138)
	at xyz.acproject.danmuji.service.impl.SetServiceImpl.holdSet(SetServiceImpl.java:330)
	at xyz.acproject.danmuji.service.impl.ClientServiceImpl.startConnService(ClientServiceImpl.java:93)
	at xyz.acproject.danmuji.controller.WebController.connectRoom(WebController.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
2021-05-04 16:33:28,198 ERROR SetServiceImpl:270 -读取配置文件历史房间失败:java.lang.NullPointerException: Cannot invoke "xyz.acproject.danmuji.conf.set.ThankWelcomeSetConf.isIs_tx_shield()" because the return value of "xyz.acproject.danmuji.conf.CenterSetConf.getWelcome()" is null

**Comment by BanqiJane** [comment]
是不是用了导入配置的功能 我本地复现了 但是退出弹幕姬  重新打开恢复正常

**Comment by BanqiJane** [comment]
模拟步骤 ： 导入2.4.3的旧版本配置-> 连接房间（此时报错）-> 退出弹幕姬  -> 重新打开弹幕姬（使用正常） 
可能原因 ： 导入配置 新设置在配置文件里面为null
待修复.....

**Comment by yaalyy** [comment]
1.有没有可能和系统或者jdk版本有关联，我用的是macOS，jdk15
2. 我这边所有和欢迎关注有关的功能都没有效果，甚至在没有登录的状态下，欢迎姬设置是可输入状态
3. 在连接房间之前，保存后显示 DEBUG SetServiceImpl:243 -保存配置文件成功，然而刷新之后，欢迎姬仍然是初始状态
4. 连接房间之后，显示  SetServiceImpl:270 -读取配置文件历史房间失败:java.lang.NullPointerException: Cannot invoke "xyz.acproject.danmuji.conf.set.ThankWelcomeSetConf.isIs_tx_shield()" because the return value of "xyz.acproject.danmuji.conf.CenterSetConf.getWelcome()" is null。。。
此时保存设置会显示 ERROR SetServiceImpl:246 -保存配置文件失败:java.lang.NullPointerException: Cannot invoke "xyz.acproject.danmuji.conf.set.ThankWelcomeSetConf.isIs_tx_shield()" because the return value of "xyz.acproject.danmuji.conf.CenterSetConf.getWelcome()" is null
5. 目前我的设备不能正常使用2.4.4版本，还在用2.4.3老版本

**Comment by BanqiJane** [comment]
2.4.3版本在您的设备上所有功能都能正常运行么

**Comment by yaalyy** [comment]
> 2.4.3版本在您的设备上所有功能都能正常运行么

是的,除了下面的实验性功能没试过，目前我使用过的功能都是正常工作的

**Comment by BanqiJane** [comment]
[libs.zip](https://github.com/BanqiJane/Bilibili_Danmuji/files/6449839/libs.zip)
试一下这个
