### ISSUE TITLE
2.7.0.1版本疑似异常退出登录

### ISSUE THREAD

**Issue by xialei123456** [BanqiJane/Bilibili_Danmuji#95]
查阅日志如下，表现为自动·1退出登录，此前是通过扫码正常登录使用的状态。运行与Ubuntu20.04，挂screen运行
启动参数为 java -jar -Xms64m -Xmx128m  BiliBili_Danmuji-2.7.0.1beta.jar --server.port=2333
 
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03q0xe90x04f0x1e}0x050x8b0x830x1b)#0xb4y0xf9u0xe70x08n0xfc0xbcF0xcf0x040xd3b0x000x0cm|0xce2 ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:419) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:271) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.63.jar!/:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_402]
2024-06-06 21:25:03,948 INFO  SetServiceImpl:302 -用户退出成功
2024-06-06 21:25:55,976 INFO  Websocket:58 -websocket connect close(连接已经断开)，纠错码:1006
2024-06-06 21:25:55,976 ERROR Websocket:84 -[错误信息，请将log文件下的日志发送给管理员]websocket connect error,message:null

**Comment by BanqiJane** [comment]
日志前面那一串 应该是带奇怪参数的外部访问，日志体现出的用户退出是手动退出的，会不会是token过期导致的自动退出登陆

**Comment by xialei123456** [comment]
> 日志前面那一串应该是带奇怪参数的外部访问，日志体现出的用户退出是手动退出的，会不会是token过期导致的自动退出登陆。 可以上传完整的日志文件吗

谢佬回复，token的话应该没有过期，是近几天扫码登录的，完整日志如下，谢佬！
[log.zip](https://github.com/user-attachments/files/15735604/log.zip)
